var dares = [
    'Give someone a piggyback ride',
    'Do not blink for a minute',
'Any time someone takes a drink, ask them for a sip',
'Do your best Buzz Lightyear impression',
'Run around the outside of the house three times',
'Go outside and yell “I pick my nose” to the first person you see',
'Put your leg behind your head',
'Eat a spoonful of hot sauce',
'Hug your mailbox (or a tree or lawn ornament) for 20 seconds',
'Sing the Star-Spangled Banner in your best opera voice',
'Take a bite out of a stick of butter',
'Draw a face on your hand and talk with your hand when it’s your turn',
'Let the person standing closest to you do your make-up crazy. Keep it on for at least an hour',
'Talk with your tongue sticking out',
'Do the next dare for the next person that gets one',
'Text someone using only your nose',
'Use the driveway as a catwalk for 5 minutes and wave to passing people',
'Brush your teeth in front of everyone',
'Do jumping jacks until your next turn',
'Do 10 perfect pushups',
'Go up to anyone on the street and ask “how could you?” with much emotion',
'Eat a spoonful of mustard',
'Play the air guitar',
    'Tie your shoes together, and try not to forget!',
    'Stick round labels all over yourself and pretend to have chickenpox',
'Sing Un Poco Loco',
'Spin around 10 times and try to walk a straight line',
'Pretend to have chicken pox by sticking around labels all over yourself',
'Skip instead of walking or running',
'Run around wearing socks on your hands, pants for a shirt, and a shirt for pants, for 3 minutes',
'Eat a pudding cup without using your hands',
'Wear underwear on your head for the rest of the game',
'Stuff as many marshmallows in your mouth as possible',
'Let the person next to you do your makeup any way they’d like',
'Say the alphabet backward as fast as you can',
'Touch your nose with your tongue',
'Chug a cup of (milk, water, juice, etc.)',
'Talk and act like a robot',
'Blindfold yourself for your next 3 turns',
'Ask someone to tango',
'Act like a gorilla and pretend to pick bugs out of your friend’s hair',
'Do the cha-cha until it is your turn again',
'Make animal sounds for a minute straight',
];