var truths = ['Who is your favorite teacher?',
    'What is a word that you’ve made up?',
    'What is your favorite meal Mom makes?',
    'Have you ever lied about your age?',
    'Would you rather have a pet or a sibling?',
    'What was the biggest joke you’ve ever played on someone?',
    'Do you have a unique talent?',
    'Do you sing in the shower?',
    'Who would win in a fight- Hulk or Iron Man?',
    'Have you ever peed the bed?',
    'What one thing are you always losing track of?',
    'How do you cheat on a chore?',
    'When was the last time you were bored out of your brains?',
    'How often do you floss your teeth?',
    'Which celebrity would you be, and why?',
    'Are you a dog person or a cat person?',
    'Are you afraid of ghosts?',
    'Which are the funniest words you know?',
    'Have you poured a glass of milk on a plant?',
    'Have you ever broken something and not told anyone?',
    'Have you ever cried during a movie?',
    'Do you apologize after an argument?',
    'If you had 1 minute to get out of your house, what would you grab?',
    'Do you think rain smells good?',
    'If you had a pet dinosaur, which would you pick?',
    'Have you ever skipped school?',
        'What do you want to do when you grow up?',
        'Would you rather go to the beach or the mountains?',
        'What is your favorite meal?',
        'Do you like romantic movies?',
        'Which superhero do you dig the most?',
        'What is your nickname?',
        'What is the least favorite gift you’ve ever received?',
    'What would you do if you were a giant?',
    'Do you like hot dogs?',
    'Can you give directions to the closest grocery store?',
    'Have you been called a snitch?',
    'What is a bad habit that you have?',
    'Have you ever peeked at Christmas presents early?',
    'What is your favorite sport?',
    'When is the last time your room saw a vacuum?',
    'If you get hold of a time machine, ‘when’ would you like to go?',
    'What is the first that you do after school?',
    'Is there anything hidden under your bed?',
    'Which would you rather have for dinner: fast-food or Mom’s home cooking?',
    'Do you have a cell phone?',
    'When is the last time you sincerely apologized?',
    'Have you poured salt on a slug?',
    'What would be your new name if you were allowed to choose one?',
    'What do you like most about everyone in the room?',
    'Have you skipped school?',
    'Do you have hidden snacks in your room?',
    'Who is your favorite superhero?',
    'Have you ever cried during a movie? If so, which one?',
    'What’s the dumbest thing you ever said or did, around a boy/girl you liked?',
    'Do you bite your nails?'
];